language: node_js
node_js:
- '6'
- '4'
- '0.12'
- '0.10'
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: pgt+2M3RLZhTq8Ga7tOZZg3E50fEc0S/wE7aZA+VwHIhDnpJEhcoyU1o56mXzMR+KU3L5pS3jRnoQDjiy2avbWAyghshs61ti9ZGgNByv5vfTUAVfyHztvTtOHU/bLJlj7KqBS8e5lngBWZsHuMaKFguvv34zf1FfTgGJrLh8YXt5PE3c23uzemsb9D2ezi57Fx39xUgO0LNkImLnSQGdkKQuVYz5iLNSJcKUPMCmjoQTtpKRp2ssV4sQyFyxtSBR4FeQj8qMikgxuo3PotZeDrv6X4Ch0VIOJ8ZTvlEuxHzVFwmJDNgseR2+ZAHnZDKAK281SbGgAq7SLd9SH6CG2asd1f9HhhyCUkIy2yAO8OEuQoCYOH8GYVGp51XMda/Y+WjeoZQfGZqYxSIpPuE+8KOG0l7NCROcOf6cP8+8FLYW8pYLWkg54OTrhQrnCGauFF1kkoJeWBZsvHm6kUFYLVa+ZCh1PX0OFq7WhuTeoznJRTH+3NY7T+mtHUiQ+7zdV3nvYds3qlu3KU6DBnXVbO9EjUOKPQJypDODoQ2ocTYwNH3ujNQPC+zS0FKth9lqCq56MzDg5XJN3wiSCntLao8TrAqaIo8wld7u1MFkJ1osGptOc2rq1phoCu0YkzBZj7UDbfCYvtzSOc5RS0cuSvcYps+7QOiqx7RialJ1gw=
